org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Вимикаємо демона Kotlin для уникнення блокування файлів кешу
kotlin.compiler.execution.strategy=in-process

# Вимикаємо інкрементальну компіляцію Kotlin
kotlin.incremental=false

# Вимикаємо Build Tools API
kotlin.compiler.useBuildToolsApi=false
